export const SPECIALIZATIONS = [
  "General Physician",
  "Family Medicine",
  "Internal Medicine",
  "Cardiologist",
  "Endocrinologist",
  "Diabetologist",
  "Pediatrician",
  "Gynecologist",
  "Obstetrician",
  "Dermatologist",
  "Orthopedic",
  "Neurologist",
  "Neurosurgeon",
  "Psychiatrist",
  "Psychologist",
  "Pulmonologist",
  "Gastroenterologist",
  "Hepatologist",
  "Nephrologist",
  "Urologist",
  "Oncologist",
  "Hematologist",
  "Rheumatologist",
  "ENT Specialist",
  "Ophthalmologist",
  "Dentist",
  "Radiologist",
  "Pathologist",
  "General Surgeon",
  "Cardiothoracic Surgeon",
  "Plastic Surgeon",
  "Anesthesiologist",
  "Emergency Medicine",
  "Infectious Disease Specialist",
  "Geriatrician",
  "Sports Medicine",
  "Physiotherapist",
  "Nutritionist",
  "Dietitian",
  "Allergist",
];

export const SPOKEN_LANGUAGES = [
  "Nepali",
  "English",
  "Hindi",
  "Maithili",
  "Bhojpuri",
  "Newari",
  "Tamang",
  "Tharu",
  "Magar",
  "Gurung",
  "Rai",
  "Limbu",
  "Sherpa",
  "Awadhi",
  "Doteli",
];
